package view;

import com.toedter.calendar.JDateChooser;
import controller.KhachHangController;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import utils.DataValidator;

/**
 *
 * @author khanhnguyen
 */
public class KhachHangJPanel extends javax.swing.JPanel {

    private final KhachHangController khachHangController;

    /**
     * Creates new form TrangChuJPanel
     *
     * @throws java.lang.ClassNotFoundException
     */
    public KhachHangJPanel() throws ClassNotFoundException {
        initComponents();
        khachHangController = new KhachHangController(this);
        loadKhachHangData();

        // Bắt sự kiện trường Search
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

    }

    public JTable getjTableKhachHang() {
        return jTableKhachHang;
    }

    public JComboBox<String> getjCbGioiTinh() {
        return jCbGioiTinh;
    }

    public void setjCbGioiTinh(JComboBox<String> jCbGioiTinh) {
        this.jCbGioiTinh = jCbGioiTinh;
    }

    public JComboBox<String> getjCbLoaiKH() {
        return jCbLoaiKH;
    }

    public void setjCbLoaiKH(JComboBox<String> jCbLoaiKH) {
        this.jCbLoaiKH = jCbLoaiKH;
    }

    public JDateChooser getjDateNgaySinh() {
        return jDateNgaySinh;
    }

    public void setjDateNgaySinh(JDateChooser jDateNgaySinh) {
        this.jDateNgaySinh = jDateNgaySinh;
    }

    public JTextField getjTextDiaChi() {
        return jTextDiaChi;
    }

    public void setjTextDiaChi(JTextField jTextDiaChi) {
        this.jTextDiaChi = jTextDiaChi;
    }

    public JTextField getjTextDienThoai() {
        return jTextDienThoai;
    }

    public void setjTextDienThoai(JTextField jTextDienThoai) {
        this.jTextDienThoai = jTextDienThoai;
    }

    public JTextField getjTextEmail() {
        return jTextEmail;
    }

    public void setjTextEmail(JTextField jTextEmail) {
        this.jTextEmail = jTextEmail;
    }

    public JTextField getjTextMaKH() {
        return jTextMaKH;
    }

    public void setjTextMaKH(JTextField jTextMaKH) {
        this.jTextMaKH = jTextMaKH;
    }

    public JTextField getjTextTenKH() {
        return jTextTenKH;
    }

    public void setjTextTenKH(JTextField jTextTenKH) {
        this.jTextTenKH = jTextTenKH;
    }

    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) jTableKhachHang.getModel();
    }

    // Load bảng sản phầm
    public void loadKhachHangData() throws ClassNotFoundException {
        List<KhachHang> khachHangList = khachHangController.getAllKhachHang();
        DefaultTableModel model = (DefaultTableModel) jTableKhachHang.getModel();
        model.setRowCount(0);

        for (KhachHang kh : khachHangList) {
            model.addRow(new Object[]{
                kh.getMaKh(),
                kh.getTenKh(),
                kh.getNgaySinh(),
                kh.getGioiTinh(),
                kh.getDiaChi(),
                kh.getDienThoai(),
                kh.getEmail(),
                kh.getLoaiKh()
            });
        }

    }

    // Xoá các trường
    private void clearFormField() {
        jTextMaKH.setText("");
        jTextTenKH.setText("");
        jTextDiaChi.setText("");
        jTextDienThoai.setText("");
        jTextEmail.setText("");
        jDateNgaySinh.setDate(null);
        jCbGioiTinh.setSelectedIndex(0);
        jCbLoaiKH.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhachHang = new javax.swing.JTable();
        jlbAdd = new javax.swing.JLabel();
        jlbUpdate = new javax.swing.JLabel();
        jlbDelete = new javax.swing.JLabel();
        jlbPrint = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbCSV = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlbExcel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCbSearch = new javax.swing.JComboBox<>();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelMaKH = new javax.swing.JLabel();
        jTextMaKH = new javax.swing.JTextField();
        jLabelTenKH = new javax.swing.JLabel();
        jTextTenKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabelNgaySinh = new javax.swing.JLabel();
        jDateNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jCbGioiTinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextDiaChi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextDienThoai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCbLoaiKH = new javax.swing.JComboBox<>();
        jTextEmail = new javax.swing.JTextField();
        jlbReset = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jpnView.setBackground(new java.awt.Color(255, 255, 255));

        jTableKhachHang.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jTableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Birthday", "Sex", "Address", "Phone", "Email", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableKhachHang.getTableHeader().setReorderingAllowed(false);
        jTableKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKhachHang);

        jlbAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jlbAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAddMouseClicked(evt);
            }
        });

        jlbUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencil.png"))); // NOI18N
        jlbUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbUpdateMouseClicked(evt);
            }
        });

        jlbDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        jlbDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbDeleteMouseClicked(evt);
            }
        });

        jlbPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        jlbPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbPrintMouseClicked(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("ADD");

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("EDIT");

        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("DELETE");

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("PRINT");

        jlbCSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/csv.png"))); // NOI18N
        jlbCSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbCSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCSVMouseClicked(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText(" EXCEL");

        jlbExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/excel.png"))); // NOI18N
        jlbExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbExcelMouseClicked(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("CSV");

        jCbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Search by Customer Name", "Search by Birth Year", "Search by Address", " " }));

        jTextFieldSearch.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldSearch.setText("Type to search...");
        jTextFieldSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSearchMouseClicked(evt);
            }
        });
        jTextFieldSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSearchKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMaKH.setText("Customer ID (*)");
        jPanel1.add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 81, -1, -1));
        jPanel1.add(jTextMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 78, 177, -1));

        jLabelTenKH.setText("Name (*)");
        jPanel1.add(jLabelTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 126, -1, -1));
        jPanel1.add(jTextTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 123, 177, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Customer Information");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 25, -1, -1));

        jLabelNgaySinh.setText("Birthday (*)");
        jPanel1.add(jLabelNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 168, -1, -1));
        jPanel1.add(jDateNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 168, 177, -1));

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 216, -1, -1));

        jCbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(jCbGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 213, 178, -1));

        jLabel5.setText("Address (*)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 261, -1, -1));
        jPanel1.add(jTextDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 258, 178, -1));

        jLabel9.setText("Phone (*)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 306, -1, -1));
        jPanel1.add(jTextDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 303, 178, -1));

        jLabel11.setText("Email (*)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 351, -1, -1));

        jLabel13.setText("Type");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 396, -1, -1));

        jCbLoaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "Regular" }));
        jPanel1.add(jCbLoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 393, 178, -1));
        jPanel1.add(jTextEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 348, 178, -1));

        jlbReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh.png"))); // NOI18N
        jlbReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbResetMouseClicked(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText("REFRESH");

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpnViewLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnViewLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6))
                    .addGroup(jpnViewLayout.createSequentialGroup()
                        .addComponent(jlbAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbUpdate)))
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnViewLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jlbPrint)
                        .addGap(18, 18, 18)
                        .addComponent(jlbExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jlbReset)
                        .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbExcel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(jLabel10)
                        .addComponent(jLabel12)
                        .addComponent(jLabel15)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Nút làm mới
    private void jlbResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbResetMouseClicked
        clearFormField();
        jTableKhachHang.clearSelection();
        jTextMaKH.setEditable(true);
    }//GEN-LAST:event_jlbResetMouseClicked

    // Ô tìm kiếm
    private void jTextFieldSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchKeyPressed
        if (jTextFieldSearch.getText().isEmpty()) {
            jTextFieldSearch.setText("");
            jTextFieldSearch.setForeground(Color.BLACK);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Lấy giá trị tìm kiếm từ JTextField
            String searchTerm = jTextFieldSearch.getText().trim();

            // Lấy lựa chọn hiện tại từ ComboBox
            String selectedOption = (String) jCbSearch.getSelectedItem();

            if (!searchTerm.isEmpty()) {
                switch (selectedOption) {
                    case "All": {
                        try {
                            khachHangController.searchInAllColumns(searchTerm);
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(null, "No results found");
                        }
                        System.out.print("test");
                    }
                    jTextFieldSearch.setText("");
                    break;

                    case "Search by Customer Name":
                    khachHangController.searchByName(searchTerm);
                    jTextFieldSearch.setText("");
                    break;
                    case "Search by Birth Year":
                    khachHangController.searchByYearOfBirth(searchTerm);
                    jTextFieldSearch.setText("");
                    break;
                    case "Search by Address":
                    khachHangController.searchByAddress(searchTerm);
                    jTextFieldSearch.setText("");
                    break;
                    default:
                    JOptionPane.showMessageDialog(null, "Invalid search option!");
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTextFieldSearchKeyPressed

    private void jTextFieldSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchMouseClicked
        jTextFieldSearch.setText("");
        jTextFieldSearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextFieldSearchMouseClicked

    // Nút xuất file excel
    private void jlbExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbExcelMouseClicked
        // Gọi phương thức xuất file Excel
        khachHangController.exportToExcel();
    }//GEN-LAST:event_jlbExcelMouseClicked

    // Nút xuất file csv
    private void jlbCSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCSVMouseClicked
        try {
            // Gọi phương thức xuất file CSV
            khachHangController.exportToCSV();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlbCSVMouseClicked

    // Nút in bảng
    private void jlbPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbPrintMouseClicked
        boolean inThanhCong = true;
        try {
            inThanhCong = jTableKhachHang.print(JTable.PrintMode.FIT_WIDTH, null, null);
        } catch (PrinterException ex) {
            Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (inThanhCong) {
            JOptionPane.showMessageDialog(null, "Print successful!");
        } else {
            JOptionPane.showMessageDialog(null, "Print failed");
        }
    }//GEN-LAST:event_jlbPrintMouseClicked

    // Nút xoá
    private void jlbDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbDeleteMouseClicked
        // Chọn dòng xoá
        int selectedRow = jTableKhachHang.getSelectedRow();

        // Kiểm tra người dùng đã chọn chưa
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to update", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lấy MAKH từ dòng muốn xoá
        String maKH = jTableKhachHang.getValueAt(selectedRow, 0).toString();

        // Xác nhận xoá
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Notification", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                KhachHang khachHang = new KhachHang(maKH, "", null, "", "", "", "", "");

                // Gọi phương thức xoá
                khachHangController.deleteKhachHang(khachHang);

                // Hiển thị thông báo xoá thành
                JOptionPane.showMessageDialog(this, "Delete successful");

                // Làm mới bảng
                loadKhachHangData();
            } catch (HeadlessException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(this, ": " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jlbDeleteMouseClicked

    // Nút sửa
    private void jlbUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbUpdateMouseClicked
        String maKH = jTextMaKH.getText();
        String tenKH = jTextTenKH.getText();
        Date ngaySinh = jDateNgaySinh.getDate();
        String gioiTinh = (String) jCbGioiTinh.getSelectedItem();
        String diaChi = jTextDiaChi.getText();
        String dienThoai = jTextDienThoai.getText();
        String email = jTextEmail.getText();

        // Kiểm tra dữ liệu đã nhập đủ chưa
        if (!DataValidator.isValidDataKH(maKH, tenKH, ngaySinh, diaChi, dienThoai, email)) {
            return;
        }

        // Kiểm tra tên khách hàng
        if (!DataValidator.isValidTenKH(tenKH)) {
            return;
        }

        // Kiểm tra số điện thoại
        if (!DataValidator.isValidSoDienThoai(dienThoai)) {
            return;
        }

        // Cập nhật thông tin khách
        try {
            khachHangController.updateKhachHang();
            clearFormField();

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jlbUpdateMouseClicked

    // Nút thêm
    private void jlbAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAddMouseClicked
        String maKH = jTextMaKH.getText();
        String tenKH = jTextTenKH.getText();
        Date ngaySinh = jDateNgaySinh.getDate();
        String gioiTinh = (String) jCbGioiTinh.getSelectedItem();
        String diaChi = jTextDiaChi.getText();
        String dienThoai = jTextDienThoai.getText();
        String email = jTextEmail.getText();
        String currentEmail = khachHangController.getCurrentEmail();
        String loaiKH = (String) jCbLoaiKH.getSelectedItem();

        // Kiểm tra dữ liệu đã nhập đủ chưa
        if (!DataValidator.isValidDataKH(maKH, tenKH, ngaySinh, diaChi, dienThoai, email)) {
            return;
        }

        // Kiểm tra tên khách hàng
        if (!DataValidator.isValidTenKH(tenKH)) {
            return;
        }

        // Kiểm tra số điện thoại
        if (!DataValidator.isValidSoDienThoai(dienThoai)) {
            return;
        }

        // Kiểm tra email duy nhất
        if (!khachHangController.isValidEmail(email, currentEmail)) {
            return;
        }

        // Kiểm tra mã khách hàng có bị trùng 
        try {
            if (khachHangController.isMaKHExist(maKH)) {
                JOptionPane.showMessageDialog(this, "Customer ID already exists. Please enter a different Customer ID");
                return; 
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error checking customer ID");
            return; // Dừng thực hiện nếu có lỗi
        }

        KhachHang newKhachHang = new KhachHang(maKH, tenKH, new java.sql.Date(ngaySinh.getTime()), gioiTinh, diaChi, dienThoai, email, loaiKH);

        // Thêm khách hàng mới
        khachHangController.addKhachHang(newKhachHang);
        JOptionPane.showMessageDialog(this, "Added successful");

        try {
            // Làm mới bảng
            loadKhachHangData();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(KhachHangJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Xoá các trường dữ liệu
        clearFormField();
    }//GEN-LAST:event_jlbAddMouseClicked

    // Chọn dòng trên bảng
    private void jTableKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKhachHangMouseClicked
        // Lấy dòng đã chọn
        int selectedRow = jTableKhachHang.getSelectedRow();

        // Kiểm tra dòng đã được chọn
        if (selectedRow != -1) {
            // Lấy dữ liệu từ dòng đã chọn và đưa vào các ô nhập liệu
            String maKhachHang = (String) jTableKhachHang.getValueAt(selectedRow, 0);
            String tenKhachHang = (String) jTableKhachHang.getValueAt(selectedRow, 1);
            Date ngaySinh = (Date) jTableKhachHang.getValueAt(selectedRow, 2);
            String gioiTinh = (String) jTableKhachHang.getValueAt(selectedRow, 3);
            String diaChi = (String) jTableKhachHang.getValueAt(selectedRow, 4);
            String soDienThoai = (String) jTableKhachHang.getValueAt(selectedRow, 5);
            String email = (String) jTableKhachHang.getValueAt(selectedRow, 6);
            String loaiKhachHang = (String) jTableKhachHang.getValueAt(selectedRow, 7);

            // Đưa dữ liệu vào các ô nhập liệu
            jTextMaKH.setText(maKhachHang);
            jTextTenKH.setText(tenKhachHang);
            jDateNgaySinh.setDate(ngaySinh);
            jCbGioiTinh.setSelectedItem(gioiTinh);
            jTextDiaChi.setText(diaChi);
            jTextDienThoai.setText(soDienThoai);
            jTextEmail.setText(email);
            jCbLoaiKH.setSelectedItem(loaiKhachHang);

            // Ngăn user chỉnh sửa MAKH
            jTextMaKH.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent evt) {
                    int selectedRow = jTableKhachHang.getSelectedRow();
                    if (selectedRow != -1) {
                        // Hiển thị thông báo nếu hàng đã được chọn
                        JOptionPane.showMessageDialog(null, "You do not have permission to edit the customer ID", "Warning", JOptionPane.WARNING_MESSAGE);
                        jTextMaKH.setText(maKhachHang);
                        jTextMaKH.setEditable(false);
                    }
                }
            });

        }
    }//GEN-LAST:event_jTableKhachHangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbGioiTinh;
    private javax.swing.JComboBox<String> jCbLoaiKH;
    private javax.swing.JComboBox<String> jCbSearch;
    private com.toedter.calendar.JDateChooser jDateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelNgaySinh;
    private javax.swing.JLabel jLabelTenKH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKhachHang;
    private javax.swing.JTextField jTextDiaChi;
    private javax.swing.JTextField jTextDienThoai;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextMaKH;
    private javax.swing.JTextField jTextTenKH;
    private javax.swing.JLabel jlbAdd;
    private javax.swing.JLabel jlbCSV;
    private javax.swing.JLabel jlbDelete;
    private javax.swing.JLabel jlbExcel;
    private javax.swing.JLabel jlbPrint;
    private javax.swing.JLabel jlbReset;
    private javax.swing.JLabel jlbUpdate;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
